/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSaasRouteImport } from './routes/_authenticated/saas'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSaasIndexRouteImport } from './routes/_authenticated/saas.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSaasSettingsRouteImport } from './routes/_authenticated/saas.settings'
import { Route as AuthenticatedSaasLicensesRouteImport } from './routes/_authenticated/saas.licenses'
import { Route as AuthenticatedSaasDomainsRouteImport } from './routes/_authenticated/saas.domains'
import { Route as AuthenticatedSaasBrandingRouteImport } from './routes/_authenticated/saas.branding'
import { Route as AuthenticatedSaasAnalyticsRouteImport } from './routes/_authenticated/saas.analytics'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppScheduleRouteImport } from './routes/_authenticated/app.schedule'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app.orders'
import { Route as AuthenticatedAppMenuRouteImport } from './routes/_authenticated/app.menu'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRoutesRouteImport } from './routes/_authenticated/admin.routes'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPurchasingRouteImport } from './routes/_authenticated/admin.purchasing'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin.promotions'
import { Route as AuthenticatedAdminProductionRouteImport } from './routes/_authenticated/admin.production'
import { Route as AuthenticatedAdminMenusRouteImport } from './routes/_authenticated/admin.menus'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminDishesRouteImport } from './routes/_authenticated/admin.dishes'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminAccountingRouteImport } from './routes/_authenticated/admin.accounting'
import { Route as AuthenticatedAdminRoutesIndexRouteImport } from './routes/_authenticated/admin.routes.index'
import { Route as AuthenticatedAdminProductionIndexRouteImport } from './routes/_authenticated/admin.production.index'
import { Route as AuthenticatedAppSettingsProfileRouteImport } from './routes/_authenticated/app.settings.profile'
import { Route as AuthenticatedAppOrdersOrderIdRouteImport } from './routes/_authenticated/app.orders.$orderId'
import { Route as AuthenticatedAppMenuDishIdRouteImport } from './routes/_authenticated/app.menu.$dishId'
import { Route as AuthenticatedAdminRoutesStopsRouteImport } from './routes/_authenticated/admin.routes.stops'
import { Route as AuthenticatedAdminRoutesIncidentsRouteImport } from './routes/_authenticated/admin.routes.incidents'
import { Route as AuthenticatedAdminRoutesDeliveriesRouteImport } from './routes/_authenticated/admin.routes.deliveries'
import { Route as AuthenticatedAdminRoutesAttemptRouteImport } from './routes/_authenticated/admin.routes.attempt'
import { Route as AuthenticatedAdminProductionPackagingRouteImport } from './routes/_authenticated/admin.production.packaging'
import { Route as AuthenticatedAdminProductionLabelsRouteImport } from './routes/_authenticated/admin.production.labels'
import { Route as AuthenticatedAdminProductionKitchenRouteImport } from './routes/_authenticated/admin.production.kitchen'
import { Route as AuthenticatedAdminProductionBatchRouteImport } from './routes/_authenticated/admin.production.batch'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSaasRoute = AuthenticatedSaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaasIndexRoute = AuthenticatedSaasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSaasRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSaasSettingsRoute =
  AuthenticatedSaasSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSaasRoute,
  } as any)
const AuthenticatedSaasLicensesRoute =
  AuthenticatedSaasLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedSaasRoute,
  } as any)
const AuthenticatedSaasDomainsRoute =
  AuthenticatedSaasDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedSaasRoute,
  } as any)
const AuthenticatedSaasBrandingRoute =
  AuthenticatedSaasBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedSaasRoute,
  } as any)
const AuthenticatedSaasAnalyticsRoute =
  AuthenticatedSaasAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedSaasRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScheduleRoute =
  AuthenticatedAppScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMenuRoute = AuthenticatedAppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoutesRoute =
  AuthenticatedAdminRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPurchasingRoute =
  AuthenticatedAdminPurchasingRouteImport.update({
    id: '/purchasing',
    path: '/purchasing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionRoute =
  AuthenticatedAdminProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMenusRoute = AuthenticatedAdminMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDishesRoute =
  AuthenticatedAdminDishesRouteImport.update({
    id: '/dishes',
    path: '/dishes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountingRoute =
  AuthenticatedAdminAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoutesIndexRoute =
  AuthenticatedAdminRoutesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminRoutesRoute,
  } as any)
const AuthenticatedAdminProductionIndexRoute =
  AuthenticatedAdminProductionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductionRoute,
  } as any)
const AuthenticatedAppSettingsProfileRoute =
  AuthenticatedAppSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppOrdersOrderIdRoute =
  AuthenticatedAppOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAppOrdersRoute,
  } as any)
const AuthenticatedAppMenuDishIdRoute =
  AuthenticatedAppMenuDishIdRouteImport.update({
    id: '/$dishId',
    path: '/$dishId',
    getParentRoute: () => AuthenticatedAppMenuRoute,
  } as any)
const AuthenticatedAdminRoutesStopsRoute =
  AuthenticatedAdminRoutesStopsRouteImport.update({
    id: '/stops',
    path: '/stops',
    getParentRoute: () => AuthenticatedAdminRoutesRoute,
  } as any)
const AuthenticatedAdminRoutesIncidentsRoute =
  AuthenticatedAdminRoutesIncidentsRouteImport.update({
    id: '/incidents',
    path: '/incidents',
    getParentRoute: () => AuthenticatedAdminRoutesRoute,
  } as any)
const AuthenticatedAdminRoutesDeliveriesRoute =
  AuthenticatedAdminRoutesDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedAdminRoutesRoute,
  } as any)
const AuthenticatedAdminRoutesAttemptRoute =
  AuthenticatedAdminRoutesAttemptRouteImport.update({
    id: '/attempt',
    path: '/attempt',
    getParentRoute: () => AuthenticatedAdminRoutesRoute,
  } as any)
const AuthenticatedAdminProductionPackagingRoute =
  AuthenticatedAdminProductionPackagingRouteImport.update({
    id: '/packaging',
    path: '/packaging',
    getParentRoute: () => AuthenticatedAdminProductionRoute,
  } as any)
const AuthenticatedAdminProductionLabelsRoute =
  AuthenticatedAdminProductionLabelsRouteImport.update({
    id: '/labels',
    path: '/labels',
    getParentRoute: () => AuthenticatedAdminProductionRoute,
  } as any)
const AuthenticatedAdminProductionKitchenRoute =
  AuthenticatedAdminProductionKitchenRouteImport.update({
    id: '/kitchen',
    path: '/kitchen',
    getParentRoute: () => AuthenticatedAdminProductionRoute,
  } as any)
const AuthenticatedAdminProductionBatchRoute =
  AuthenticatedAdminProductionBatchRouteImport.update({
    id: '/batch',
    path: '/batch',
    getParentRoute: () => AuthenticatedAdminProductionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/driver': typeof AuthenticatedDriverRoute
  '/saas': typeof AuthenticatedSaasRouteWithChildren
  '/admin/accounting': typeof AuthenticatedAdminAccountingRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dishes': typeof AuthenticatedAdminDishesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/admin/production': typeof AuthenticatedAdminProductionRouteWithChildren
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/purchasing': typeof AuthenticatedAdminPurchasingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/app/menu': typeof AuthenticatedAppMenuRouteWithChildren
  '/app/orders': typeof AuthenticatedAppOrdersRouteWithChildren
  '/app/schedule': typeof AuthenticatedAppScheduleRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/saas/analytics': typeof AuthenticatedSaasAnalyticsRoute
  '/saas/branding': typeof AuthenticatedSaasBrandingRoute
  '/saas/domains': typeof AuthenticatedSaasDomainsRoute
  '/saas/licenses': typeof AuthenticatedSaasLicensesRoute
  '/saas/settings': typeof AuthenticatedSaasSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/saas/': typeof AuthenticatedSaasIndexRoute
  '/admin/production/batch': typeof AuthenticatedAdminProductionBatchRoute
  '/admin/production/kitchen': typeof AuthenticatedAdminProductionKitchenRoute
  '/admin/production/labels': typeof AuthenticatedAdminProductionLabelsRoute
  '/admin/production/packaging': typeof AuthenticatedAdminProductionPackagingRoute
  '/admin/routes/attempt': typeof AuthenticatedAdminRoutesAttemptRoute
  '/admin/routes/deliveries': typeof AuthenticatedAdminRoutesDeliveriesRoute
  '/admin/routes/incidents': typeof AuthenticatedAdminRoutesIncidentsRoute
  '/admin/routes/stops': typeof AuthenticatedAdminRoutesStopsRoute
  '/app/menu/$dishId': typeof AuthenticatedAppMenuDishIdRoute
  '/app/orders/$orderId': typeof AuthenticatedAppOrdersOrderIdRoute
  '/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/admin/production/': typeof AuthenticatedAdminProductionIndexRoute
  '/admin/routes/': typeof AuthenticatedAdminRoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/admin/accounting': typeof AuthenticatedAdminAccountingRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/dishes': typeof AuthenticatedAdminDishesRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/purchasing': typeof AuthenticatedAdminPurchasingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/app/menu': typeof AuthenticatedAppMenuRouteWithChildren
  '/app/orders': typeof AuthenticatedAppOrdersRouteWithChildren
  '/app/schedule': typeof AuthenticatedAppScheduleRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/saas/analytics': typeof AuthenticatedSaasAnalyticsRoute
  '/saas/branding': typeof AuthenticatedSaasBrandingRoute
  '/saas/domains': typeof AuthenticatedSaasDomainsRoute
  '/saas/licenses': typeof AuthenticatedSaasLicensesRoute
  '/saas/settings': typeof AuthenticatedSaasSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/saas': typeof AuthenticatedSaasIndexRoute
  '/admin/production/batch': typeof AuthenticatedAdminProductionBatchRoute
  '/admin/production/kitchen': typeof AuthenticatedAdminProductionKitchenRoute
  '/admin/production/labels': typeof AuthenticatedAdminProductionLabelsRoute
  '/admin/production/packaging': typeof AuthenticatedAdminProductionPackagingRoute
  '/admin/routes/attempt': typeof AuthenticatedAdminRoutesAttemptRoute
  '/admin/routes/deliveries': typeof AuthenticatedAdminRoutesDeliveriesRoute
  '/admin/routes/incidents': typeof AuthenticatedAdminRoutesIncidentsRoute
  '/admin/routes/stops': typeof AuthenticatedAdminRoutesStopsRoute
  '/app/menu/$dishId': typeof AuthenticatedAppMenuDishIdRoute
  '/app/orders/$orderId': typeof AuthenticatedAppOrdersOrderIdRoute
  '/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/admin/production': typeof AuthenticatedAdminProductionIndexRoute
  '/admin/routes': typeof AuthenticatedAdminRoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/saas': typeof AuthenticatedSaasRouteWithChildren
  '/_authenticated/admin/accounting': typeof AuthenticatedAdminAccountingRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/dishes': typeof AuthenticatedAdminDishesRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/menus': typeof AuthenticatedAdminMenusRoute
  '/_authenticated/admin/production': typeof AuthenticatedAdminProductionRouteWithChildren
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/purchasing': typeof AuthenticatedAdminPurchasingRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/routes': typeof AuthenticatedAdminRoutesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/app/menu': typeof AuthenticatedAppMenuRouteWithChildren
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRouteWithChildren
  '/_authenticated/app/schedule': typeof AuthenticatedAppScheduleRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/saas/analytics': typeof AuthenticatedSaasAnalyticsRoute
  '/_authenticated/saas/branding': typeof AuthenticatedSaasBrandingRoute
  '/_authenticated/saas/domains': typeof AuthenticatedSaasDomainsRoute
  '/_authenticated/saas/licenses': typeof AuthenticatedSaasLicensesRoute
  '/_authenticated/saas/settings': typeof AuthenticatedSaasSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/saas/': typeof AuthenticatedSaasIndexRoute
  '/_authenticated/admin/production/batch': typeof AuthenticatedAdminProductionBatchRoute
  '/_authenticated/admin/production/kitchen': typeof AuthenticatedAdminProductionKitchenRoute
  '/_authenticated/admin/production/labels': typeof AuthenticatedAdminProductionLabelsRoute
  '/_authenticated/admin/production/packaging': typeof AuthenticatedAdminProductionPackagingRoute
  '/_authenticated/admin/routes/attempt': typeof AuthenticatedAdminRoutesAttemptRoute
  '/_authenticated/admin/routes/deliveries': typeof AuthenticatedAdminRoutesDeliveriesRoute
  '/_authenticated/admin/routes/incidents': typeof AuthenticatedAdminRoutesIncidentsRoute
  '/_authenticated/admin/routes/stops': typeof AuthenticatedAdminRoutesStopsRoute
  '/_authenticated/app/menu/$dishId': typeof AuthenticatedAppMenuDishIdRoute
  '/_authenticated/app/orders/$orderId': typeof AuthenticatedAppOrdersOrderIdRoute
  '/_authenticated/app/settings/profile': typeof AuthenticatedAppSettingsProfileRoute
  '/_authenticated/admin/production/': typeof AuthenticatedAdminProductionIndexRoute
  '/_authenticated/admin/routes/': typeof AuthenticatedAdminRoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/app'
    | '/driver'
    | '/saas'
    | '/admin/accounting'
    | '/admin/customers'
    | '/admin/dishes'
    | '/admin/inventory'
    | '/admin/menus'
    | '/admin/production'
    | '/admin/promotions'
    | '/admin/purchasing'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/support'
    | '/app/menu'
    | '/app/orders'
    | '/app/schedule'
    | '/app/settings'
    | '/saas/analytics'
    | '/saas/branding'
    | '/saas/domains'
    | '/saas/licenses'
    | '/saas/settings'
    | '/admin/'
    | '/app/'
    | '/saas/'
    | '/admin/production/batch'
    | '/admin/production/kitchen'
    | '/admin/production/labels'
    | '/admin/production/packaging'
    | '/admin/routes/attempt'
    | '/admin/routes/deliveries'
    | '/admin/routes/incidents'
    | '/admin/routes/stops'
    | '/app/menu/$dishId'
    | '/app/orders/$orderId'
    | '/app/settings/profile'
    | '/admin/production/'
    | '/admin/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/driver'
    | '/admin/accounting'
    | '/admin/customers'
    | '/admin/dishes'
    | '/admin/inventory'
    | '/admin/menus'
    | '/admin/promotions'
    | '/admin/purchasing'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/support'
    | '/app/menu'
    | '/app/orders'
    | '/app/schedule'
    | '/app/settings'
    | '/saas/analytics'
    | '/saas/branding'
    | '/saas/domains'
    | '/saas/licenses'
    | '/saas/settings'
    | '/admin'
    | '/app'
    | '/saas'
    | '/admin/production/batch'
    | '/admin/production/kitchen'
    | '/admin/production/labels'
    | '/admin/production/packaging'
    | '/admin/routes/attempt'
    | '/admin/routes/deliveries'
    | '/admin/routes/incidents'
    | '/admin/routes/stops'
    | '/app/menu/$dishId'
    | '/app/orders/$orderId'
    | '/app/settings/profile'
    | '/admin/production'
    | '/admin/routes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/driver'
    | '/_authenticated/saas'
    | '/_authenticated/admin/accounting'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/dishes'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/menus'
    | '/_authenticated/admin/production'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/purchasing'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/routes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/app/menu'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/schedule'
    | '/_authenticated/app/settings'
    | '/_authenticated/saas/analytics'
    | '/_authenticated/saas/branding'
    | '/_authenticated/saas/domains'
    | '/_authenticated/saas/licenses'
    | '/_authenticated/saas/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/saas/'
    | '/_authenticated/admin/production/batch'
    | '/_authenticated/admin/production/kitchen'
    | '/_authenticated/admin/production/labels'
    | '/_authenticated/admin/production/packaging'
    | '/_authenticated/admin/routes/attempt'
    | '/_authenticated/admin/routes/deliveries'
    | '/_authenticated/admin/routes/incidents'
    | '/_authenticated/admin/routes/stops'
    | '/_authenticated/app/menu/$dishId'
    | '/_authenticated/app/orders/$orderId'
    | '/_authenticated/app/settings/profile'
    | '/_authenticated/admin/production/'
    | '/_authenticated/admin/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saas': {
      id: '/_authenticated/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof AuthenticatedSaasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saas/': {
      id: '/_authenticated/saas/'
      path: '/'
      fullPath: '/saas/'
      preLoaderRoute: typeof AuthenticatedSaasIndexRouteImport
      parentRoute: typeof AuthenticatedSaasRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/saas/settings': {
      id: '/_authenticated/saas/settings'
      path: '/settings'
      fullPath: '/saas/settings'
      preLoaderRoute: typeof AuthenticatedSaasSettingsRouteImport
      parentRoute: typeof AuthenticatedSaasRoute
    }
    '/_authenticated/saas/licenses': {
      id: '/_authenticated/saas/licenses'
      path: '/licenses'
      fullPath: '/saas/licenses'
      preLoaderRoute: typeof AuthenticatedSaasLicensesRouteImport
      parentRoute: typeof AuthenticatedSaasRoute
    }
    '/_authenticated/saas/domains': {
      id: '/_authenticated/saas/domains'
      path: '/domains'
      fullPath: '/saas/domains'
      preLoaderRoute: typeof AuthenticatedSaasDomainsRouteImport
      parentRoute: typeof AuthenticatedSaasRoute
    }
    '/_authenticated/saas/branding': {
      id: '/_authenticated/saas/branding'
      path: '/branding'
      fullPath: '/saas/branding'
      preLoaderRoute: typeof AuthenticatedSaasBrandingRouteImport
      parentRoute: typeof AuthenticatedSaasRoute
    }
    '/_authenticated/saas/analytics': {
      id: '/_authenticated/saas/analytics'
      path: '/analytics'
      fullPath: '/saas/analytics'
      preLoaderRoute: typeof AuthenticatedSaasAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSaasRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/schedule': {
      id: '/_authenticated/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AuthenticatedAppScheduleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/menu': {
      id: '/_authenticated/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AuthenticatedAppMenuRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/routes': {
      id: '/_authenticated/admin/routes'
      path: '/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthenticatedAdminRoutesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/purchasing': {
      id: '/_authenticated/admin/purchasing'
      path: '/purchasing'
      fullPath: '/admin/purchasing'
      preLoaderRoute: typeof AuthenticatedAdminPurchasingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/production': {
      id: '/_authenticated/admin/production'
      path: '/production'
      fullPath: '/admin/production'
      preLoaderRoute: typeof AuthenticatedAdminProductionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menus': {
      id: '/_authenticated/admin/menus'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AuthenticatedAdminMenusRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dishes': {
      id: '/_authenticated/admin/dishes'
      path: '/dishes'
      fullPath: '/admin/dishes'
      preLoaderRoute: typeof AuthenticatedAdminDishesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounting': {
      id: '/_authenticated/admin/accounting'
      path: '/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AuthenticatedAdminAccountingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/routes/': {
      id: '/_authenticated/admin/routes/'
      path: '/'
      fullPath: '/admin/routes/'
      preLoaderRoute: typeof AuthenticatedAdminRoutesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoutesRoute
    }
    '/_authenticated/admin/production/': {
      id: '/_authenticated/admin/production/'
      path: '/'
      fullPath: '/admin/production/'
      preLoaderRoute: typeof AuthenticatedAdminProductionIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductionRoute
    }
    '/_authenticated/app/settings/profile': {
      id: '/_authenticated/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AuthenticatedAppSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/orders/$orderId': {
      id: '/_authenticated/app/orders/$orderId'
      path: '/$orderId'
      fullPath: '/app/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAppOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAppOrdersRoute
    }
    '/_authenticated/app/menu/$dishId': {
      id: '/_authenticated/app/menu/$dishId'
      path: '/$dishId'
      fullPath: '/app/menu/$dishId'
      preLoaderRoute: typeof AuthenticatedAppMenuDishIdRouteImport
      parentRoute: typeof AuthenticatedAppMenuRoute
    }
    '/_authenticated/admin/routes/stops': {
      id: '/_authenticated/admin/routes/stops'
      path: '/stops'
      fullPath: '/admin/routes/stops'
      preLoaderRoute: typeof AuthenticatedAdminRoutesStopsRouteImport
      parentRoute: typeof AuthenticatedAdminRoutesRoute
    }
    '/_authenticated/admin/routes/incidents': {
      id: '/_authenticated/admin/routes/incidents'
      path: '/incidents'
      fullPath: '/admin/routes/incidents'
      preLoaderRoute: typeof AuthenticatedAdminRoutesIncidentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoutesRoute
    }
    '/_authenticated/admin/routes/deliveries': {
      id: '/_authenticated/admin/routes/deliveries'
      path: '/deliveries'
      fullPath: '/admin/routes/deliveries'
      preLoaderRoute: typeof AuthenticatedAdminRoutesDeliveriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoutesRoute
    }
    '/_authenticated/admin/routes/attempt': {
      id: '/_authenticated/admin/routes/attempt'
      path: '/attempt'
      fullPath: '/admin/routes/attempt'
      preLoaderRoute: typeof AuthenticatedAdminRoutesAttemptRouteImport
      parentRoute: typeof AuthenticatedAdminRoutesRoute
    }
    '/_authenticated/admin/production/packaging': {
      id: '/_authenticated/admin/production/packaging'
      path: '/packaging'
      fullPath: '/admin/production/packaging'
      preLoaderRoute: typeof AuthenticatedAdminProductionPackagingRouteImport
      parentRoute: typeof AuthenticatedAdminProductionRoute
    }
    '/_authenticated/admin/production/labels': {
      id: '/_authenticated/admin/production/labels'
      path: '/labels'
      fullPath: '/admin/production/labels'
      preLoaderRoute: typeof AuthenticatedAdminProductionLabelsRouteImport
      parentRoute: typeof AuthenticatedAdminProductionRoute
    }
    '/_authenticated/admin/production/kitchen': {
      id: '/_authenticated/admin/production/kitchen'
      path: '/kitchen'
      fullPath: '/admin/production/kitchen'
      preLoaderRoute: typeof AuthenticatedAdminProductionKitchenRouteImport
      parentRoute: typeof AuthenticatedAdminProductionRoute
    }
    '/_authenticated/admin/production/batch': {
      id: '/_authenticated/admin/production/batch'
      path: '/batch'
      fullPath: '/admin/production/batch'
      preLoaderRoute: typeof AuthenticatedAdminProductionBatchRouteImport
      parentRoute: typeof AuthenticatedAdminProductionRoute
    }
  }
}

interface AuthenticatedAdminProductionRouteChildren {
  AuthenticatedAdminProductionBatchRoute: typeof AuthenticatedAdminProductionBatchRoute
  AuthenticatedAdminProductionKitchenRoute: typeof AuthenticatedAdminProductionKitchenRoute
  AuthenticatedAdminProductionLabelsRoute: typeof AuthenticatedAdminProductionLabelsRoute
  AuthenticatedAdminProductionPackagingRoute: typeof AuthenticatedAdminProductionPackagingRoute
  AuthenticatedAdminProductionIndexRoute: typeof AuthenticatedAdminProductionIndexRoute
}

const AuthenticatedAdminProductionRouteChildren: AuthenticatedAdminProductionRouteChildren =
  {
    AuthenticatedAdminProductionBatchRoute:
      AuthenticatedAdminProductionBatchRoute,
    AuthenticatedAdminProductionKitchenRoute:
      AuthenticatedAdminProductionKitchenRoute,
    AuthenticatedAdminProductionLabelsRoute:
      AuthenticatedAdminProductionLabelsRoute,
    AuthenticatedAdminProductionPackagingRoute:
      AuthenticatedAdminProductionPackagingRoute,
    AuthenticatedAdminProductionIndexRoute:
      AuthenticatedAdminProductionIndexRoute,
  }

const AuthenticatedAdminProductionRouteWithChildren =
  AuthenticatedAdminProductionRoute._addFileChildren(
    AuthenticatedAdminProductionRouteChildren,
  )

interface AuthenticatedAdminRoutesRouteChildren {
  AuthenticatedAdminRoutesAttemptRoute: typeof AuthenticatedAdminRoutesAttemptRoute
  AuthenticatedAdminRoutesDeliveriesRoute: typeof AuthenticatedAdminRoutesDeliveriesRoute
  AuthenticatedAdminRoutesIncidentsRoute: typeof AuthenticatedAdminRoutesIncidentsRoute
  AuthenticatedAdminRoutesStopsRoute: typeof AuthenticatedAdminRoutesStopsRoute
  AuthenticatedAdminRoutesIndexRoute: typeof AuthenticatedAdminRoutesIndexRoute
}

const AuthenticatedAdminRoutesRouteChildren: AuthenticatedAdminRoutesRouteChildren =
  {
    AuthenticatedAdminRoutesAttemptRoute: AuthenticatedAdminRoutesAttemptRoute,
    AuthenticatedAdminRoutesDeliveriesRoute:
      AuthenticatedAdminRoutesDeliveriesRoute,
    AuthenticatedAdminRoutesIncidentsRoute:
      AuthenticatedAdminRoutesIncidentsRoute,
    AuthenticatedAdminRoutesStopsRoute: AuthenticatedAdminRoutesStopsRoute,
    AuthenticatedAdminRoutesIndexRoute: AuthenticatedAdminRoutesIndexRoute,
  }

const AuthenticatedAdminRoutesRouteWithChildren =
  AuthenticatedAdminRoutesRoute._addFileChildren(
    AuthenticatedAdminRoutesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountingRoute: typeof AuthenticatedAdminAccountingRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDishesRoute: typeof AuthenticatedAdminDishesRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminMenusRoute: typeof AuthenticatedAdminMenusRoute
  AuthenticatedAdminProductionRoute: typeof AuthenticatedAdminProductionRouteWithChildren
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminPurchasingRoute: typeof AuthenticatedAdminPurchasingRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRoutesRoute: typeof AuthenticatedAdminRoutesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountingRoute: AuthenticatedAdminAccountingRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDishesRoute: AuthenticatedAdminDishesRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminMenusRoute: AuthenticatedAdminMenusRoute,
  AuthenticatedAdminProductionRoute:
    AuthenticatedAdminProductionRouteWithChildren,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminPurchasingRoute: AuthenticatedAdminPurchasingRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRoutesRoute: AuthenticatedAdminRoutesRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppMenuRouteChildren {
  AuthenticatedAppMenuDishIdRoute: typeof AuthenticatedAppMenuDishIdRoute
}

const AuthenticatedAppMenuRouteChildren: AuthenticatedAppMenuRouteChildren = {
  AuthenticatedAppMenuDishIdRoute: AuthenticatedAppMenuDishIdRoute,
}

const AuthenticatedAppMenuRouteWithChildren =
  AuthenticatedAppMenuRoute._addFileChildren(AuthenticatedAppMenuRouteChildren)

interface AuthenticatedAppOrdersRouteChildren {
  AuthenticatedAppOrdersOrderIdRoute: typeof AuthenticatedAppOrdersOrderIdRoute
}

const AuthenticatedAppOrdersRouteChildren: AuthenticatedAppOrdersRouteChildren =
  {
    AuthenticatedAppOrdersOrderIdRoute: AuthenticatedAppOrdersOrderIdRoute,
  }

const AuthenticatedAppOrdersRouteWithChildren =
  AuthenticatedAppOrdersRoute._addFileChildren(
    AuthenticatedAppOrdersRouteChildren,
  )

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsProfileRoute: typeof AuthenticatedAppSettingsProfileRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsProfileRoute: AuthenticatedAppSettingsProfileRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppMenuRoute: typeof AuthenticatedAppMenuRouteWithChildren
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRouteWithChildren
  AuthenticatedAppScheduleRoute: typeof AuthenticatedAppScheduleRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppMenuRoute: AuthenticatedAppMenuRouteWithChildren,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRouteWithChildren,
  AuthenticatedAppScheduleRoute: AuthenticatedAppScheduleRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedSaasRouteChildren {
  AuthenticatedSaasAnalyticsRoute: typeof AuthenticatedSaasAnalyticsRoute
  AuthenticatedSaasBrandingRoute: typeof AuthenticatedSaasBrandingRoute
  AuthenticatedSaasDomainsRoute: typeof AuthenticatedSaasDomainsRoute
  AuthenticatedSaasLicensesRoute: typeof AuthenticatedSaasLicensesRoute
  AuthenticatedSaasSettingsRoute: typeof AuthenticatedSaasSettingsRoute
  AuthenticatedSaasIndexRoute: typeof AuthenticatedSaasIndexRoute
}

const AuthenticatedSaasRouteChildren: AuthenticatedSaasRouteChildren = {
  AuthenticatedSaasAnalyticsRoute: AuthenticatedSaasAnalyticsRoute,
  AuthenticatedSaasBrandingRoute: AuthenticatedSaasBrandingRoute,
  AuthenticatedSaasDomainsRoute: AuthenticatedSaasDomainsRoute,
  AuthenticatedSaasLicensesRoute: AuthenticatedSaasLicensesRoute,
  AuthenticatedSaasSettingsRoute: AuthenticatedSaasSettingsRoute,
  AuthenticatedSaasIndexRoute: AuthenticatedSaasIndexRoute,
}

const AuthenticatedSaasRouteWithChildren =
  AuthenticatedSaasRoute._addFileChildren(AuthenticatedSaasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedSaasRoute: typeof AuthenticatedSaasRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedSaasRoute: AuthenticatedSaasRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
